FROM ubuntu:22.04
ARG USER=dotfiletest
ARG HOME=/home/$USER
RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker
RUN DEBIAN_FRONTEND=noninteractive \
  apt-get update \
  && apt-get install -y sudo \
  && rm -rf /var/lib/apt/lists/*
RUN useradd -ms /bin/bash $USER && echo "${USER}:Docker!" | chpasswd && adduser $USER sudo
USER $USER
WORKDIR $HOME
RUN mkdir .config/
COPY --chown=$USER:$USER . src/

