#!/bin/bash
# Source colors
. $HOME/.local/bin/colors-provider

TODAY=$(expr `date +'%d'` + 0)
MONTH=`date +'%m'`
YEAR=`date +'%Y'`
LINES=$(cal | wc -l)
LINES=$((LINES + 1))

(
#date +'%A, %d %b %Y %H:%M'
date +'^bg($RED) '
date +''

n30f -d -x 585 -y 48 $HOME/.config/polybar/popups/calendar/bg.png &
# current month, highlight header and today
cal | sed -r -e "1,2 s/.*/^fg($RED)&^fg()/"  -e "s/(^| )($TODAY)($|)/\1^bg(#596b79)^fg(#b5b5b5)\2^fg()^bg()\3/") | dzen2 -fn "Futura Bk BT Book:pixelsize=12" -x 590 -y 40 -w 190 -h 15 -l $LINES -tw 0 -sa c -p -e 'onstart=uncollapse,hide;button1=exit;' -fg "$foreground" -bg "$background"

pkill n30f
