#!/usr/bin/python3

from urllib.request import urlopen
import simplejson

r = urlopen("https://shapeshift.io/marketinfo/xrp_eth")
datar = simplejson.load(r)
howmanyxrp = 52.107634
eth = howmanyxrp * datar["rate"]
e = urlopen("https://api.coinbase.com/v2/prices/eth-eur/buy")
datae = simplejson.load(e)
currentvaluesineur = float(datae["data"]["amount"]) * eth
print('~','%.2f' % currentvaluesineur)
